version: '3.8'

services:
  eventstore:
    environment:
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_INSECURE: 'true'
    image: eventstore/eventstore:21.10.1-buster-slim
    networks:
      - giddup
    ports:
      - '2113:2113'
networks:
  giddup:
    name: giddup
