version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: giddup
      POSTGRES_PASSWORD: giddup
      POSTGRES_DB: giddup
    image: postgres:16.0
    networks:
      - giddup
    ports:
      - '5432:5432'

  giddup-api:
    build:
      context: .
      dockerfile: src/Giddup.Presentation.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__Postgres: 'Host=postgres; Port=5432; User ID=giddup; Password=giddup; Database=giddup; Pooling=true;'
    image: ${DOCKER_REGISTRY-}giddup-api
    networks:
      - giddup
    ports:
      - '5000:80'

networks:
  giddup:
    name: giddup
