@startuml add required reviewer

(*) --> if "is created?" then
  ->[false] "not created error"
else
  -->[true] if "status is active?" then
    ->[false] "not active error"
  else
    [true] if "reviewer already exists?" then
      ->[true] "no event"
    else
      -->[false] "required reviewer added event"
      --> (*)
    endif
  endif
endif

@enduml
